### ISSUE TITLE
Invoking/importing Junction raises PackageNotFoundError

### ISSUE THREAD

**Issue by FaridNeshat-TomTom** [HUU/Junction#31]
Hi,

Just installed junction and here's what I got:

```
$ junction
Traceback (most recent call last):
  File "/usr/local/bin/junction", line 5, in <module>
    from junction.cli import main
  File "/usr/local/lib/python3.8/site-packages/junction/__init__.py", line 3, in <module>
    __version__ = version('junction')
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 530, in version
    return distribution(distribution_name).version
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: junction
```

This happens from the following code:

```
from importlib.metadata import version

__version__ = version(__package__)
```

Since `__package__` is `confluence-junction`, but the actual importable name is `junction` and not `confluence-junction`, so  it'll throw that error.

**Comment by HUU** [comment]
Thanks for the report @FaridNeshat-TomTom -- I [released ](https://github.com/HUU/Junction/releases/tag/v0.1.1) a fix that is live on PyPI now as version 0.1.1 

```
pip install confluence-junction==0.1.1
```
